version: '3'

services:
  database:
    container_name: database
    image: postgres:alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: main
      POSTGRES_DB: xml-uploader
    ports:
      - "5432:5432"
  php:
    container_name: php
    build:
      context: .
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./artifacts/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/www/html/public
    depends_on:
      - php
      - database