version: '3'

services:
  database:
    image: postgres:alpine
    container_name: goods-test
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports: [5432]